# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: df45d036b83081eff09ec1edd06bce9abd1d61eda39f616faa1b80c3e53672d68c2162762e1423dd1098cb88adfe07c1b290acf5818cebe86f359cfae57532e1

test:
  secret_key_base: cbad43bf2ad84e342998a34b51084c575b7ac08a20514151fef0e01362a59a19bd18035d2260befc3ba545ac0d41584caa6d79d53d996883519c470ff737b10c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
